### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by JusticeByLu** [sh1newu/SepMark#8]
Thank you for providing the code, but I encountered an issue during the replication process. There was a missing image error while executing the training file Dual-Mark_main.cy. The dataset was downloaded from the provided link. The error is as follows:
Start training : 

cuda
Traceback (most recent call last):
  File "D:\PyCharm_workspace\copyrightprotection\SepMark-main\Dual_Mark_main.py", line 193, in <module>
    main()
  File "D:\PyCharm_workspace\copyrightprotection\SepMark-main\Dual_Mark_main.py", line 101, in main
    result = network.train(image, message, mask)
  File "D:\PyCharm_workspace\copyrightprotection\SepMark-main\network\Dual_Mark.py", line 52, in train
    encoded_images, noised_images, decoded_messages_C, decoded_messages_R, decoded_messages_F = self.encoder_decoder(images, messages, masks)
  File "D:\Anaconda\Anaconda\envs\SepMark\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\Anaconda\envs\SepMark\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Anaconda\Anaconda\envs\SepMark\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PyCharm_workspace\copyrightprotection\SepMark-main\network\DW_EncoderDecoder.py", line 23, in forward
    noised_image_C, noised_image_R, noised_image_F = self.noise([encoded_image, image, mask])
  File "D:\Anaconda\Anaconda\envs\SepMark\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PyCharm_workspace\copyrightprotection\SepMark-main\network\Random_Noise.py", line 35, in forward
    noised_image_F[index] = random_noise_layer_F([forward_image[index].clone().unsqueeze(0), forward_cover_image[index].clone().unsqueeze(0), forward_mask[index].clone().unsqueeze(0)])
  File "D:\Anaconda\Anaconda\envs\SepMark\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PyCharm_workspace\copyrightprotection\SepMark-main\network\noise_layers\simswap\test_one_image.py", line 61, in forward
    img_a = Image.open(pic_a).convert('RGB')
  File "D:\Anaconda\Anaconda\envs\SepMark\lib\site-packages\PIL\Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/likaide/sda4/wxs/Dataset/dual_watermark/celeba_256/val/168125.png'

**Comment by sh1newu** [comment]
Sorry for the late reply. If the issue hasn't been resolved, you should try downloading the entire dataset (celeba_256/val used for face swapping) and placing it in the correct location.
